<a href="https://colab.research.google.com/github/Charmiece/Final-Project---CreditCard-Fraud/blob/Princy/Copy_of_Final_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
# Find the latest version of spark 3.0  from http://www.apache.org/dist/spark/ and enter as the spark version
# For example:
# spark_version = 'spark-3.0.3'
spark_version = 'spark-3.0.3'
os.environ['SPARK_VERSION']=spark_version

# Install Spark and Java
!apt-get update
!apt-get install openjdk-11-jdk-headless -qq > /dev/null
!wget -q http://www.apache.org/dist/spark/$SPARK_VERSION/$SPARK_VERSION-bin-hadoop2.7.tgz
!tar xf $SPARK_VERSION-bin-hadoop2.7.tgz
!pip install -q findspark

# Set Environment Variables
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"] = f"/content/{spark_version}-bin-hadoop2.7"

# Start a SparkSession
import findspark
findspark.init()

Get:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Ign:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Ign:3 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release [696 B]
Err:5 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
  404  Not Found [IP: 152.195.19.142 443]
Hit:6 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [836 B]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:9 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:10 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease [15.9 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:12 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ Packages [80.8 kB]
Hit:13 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Get:14 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease [15.9 kB]
Get:15 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease [21.3 kB]
Get:16 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages [950 kB]
Get:17 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic/main Sources [1,830 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [911 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3,117 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2,264 kB]
Get:21 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic/main amd64 Packages [937 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [29.8 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [12.2 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [12.9 kB]
Get:25 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2,678 kB]
Get:26 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,486 kB]
Get:27 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [878 kB]
Get:28 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic/main amd64 Packages [45.3 kB]
Get:29 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic/main amd64 Packages [44.3 kB]
Reading package lists... Done
E: The repository 'https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

In [2]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("CloudETL").config("spark.driver.extraClassPath","/content/postgresql-42.2.9.jar").getOrCreate()

In [3]:
from pyspark import SparkFiles
url ="https://fraudcreditcard.s3.amazonaws.com/fraudTrain.csv"
spark.sparkContext.addFile(url)
df = spark.read.csv(SparkFiles.get("fraudTrain.csv"), sep=",", header=True)
# Show DataFrame
df.show()

+---+---------------------+-------------------+--------------------+-------------+------+-----------+---------+------+--------------------+--------------------+-----+-----+-------+------------------+--------+--------------------+----------+--------------------+----------+------------------+------------------+--------+
|_c0|trans_date_trans_time|             cc_num|            merchant|     category|   amt|      first|     last|gender|              street|                city|state|  zip|    lat|              long|city_pop|                 job|       dob|           trans_num| unix_time|         merch_lat|        merch_long|is_fraud|
+---+---------------------+-------------------+--------------------+-------------+------+-----------+---------+------+--------------------+--------------------+-----+-----+-------+------------------+--------+--------------------+----------+--------------------+----------+------------------+------------------+--------+
|  0|  2019-01-01 00:00:18|   2703186189652095|fraud_Rippin, Kub...|     misc_net|  4.97|   Jennifer|    Banks|     F|      561 Perry Cove|      Moravian Falls|   NC|28654|36.0788|          -81.1781|    3495|Psychologist, cou...|1988-03-09|0b242abb623afc578...|1325376018|         36.011293|        -82.048315|       0|
|  1|  2019-01-01 00:00:44|       630423337322|fraud_Heller, Gut...|  grocery_pos|107.23|  Stephanie|     Gill|     F|43039 Riley Green...|              Orient|   WA|99160|48.8878|         -118.2105|     149|Special education...|1978-06-21|1f76529f857473494...|1325376044|49.159046999999994|       -118.186462|       0|
|  2|  2019-01-01 00:00:51|     38859492057661|fraud_Lind-Buckridge|entertainment|220.11|     Edward|  Sanchez|     M|594 White Dale Su...|          Malad City|   ID|83252|42.1808|          -112.262|    4154|Nature conservati...|1962-01-19|a1a22d70485983eac...|1325376051|         43.150704|       -112.154481|       0|
|  3|  2019-01-01 00:01:16|   3534093764340240|fraud_Kutch, Herm...|gas_transport|  45.0|     Jeremy|    White|     M|9443 Cynthia Cour...|             Boulder|   MT|59632|46.2306|         -112.1138|    1939|     Patent attorney|1967-01-12|6b849c168bdad6f86...|1325376076|         47.034331|       -112.561071|       0|
|  4|  2019-01-01 00:03:06|    375534208663984| fraud_Keeling-Crist|     misc_pos| 41.96|      Tyler|   Garcia|     M|    408 Bradley Rest|            Doe Hill|   VA|24433|38.4207|          -79.4629|      99|Dance movement ps...|1986-03-28|a41d7549acf907893...|1325376186|         38.674999|        -78.632459|       0|
|  5|  2019-01-01 00:04:08|   4767265376804500|fraud_Stroman, Hu...|gas_transport| 94.63|   Jennifer|   Conner|     F|   4655 David Island|              Dublin|   PA|18917| 40.375|          -75.2045|    2158|   Transport planner|1961-06-19|189a841a0a8ba0305...|1325376248|         40.653382|-76.15266700000001|       0|
|  6|  2019-01-01 00:04:42|     30074693890476|fraud_Rowe-Vander...|  grocery_net| 44.54|     Kelsey| Richards|     F|889 Sarah Station...|             Holcomb|   KS|67851|37.9931|         -100.9893|    2691|     Arboriculturist|1993-08-16|83ec1cc84142af6e2...|1325376282|37.162704999999995|        -100.15337|       0|
|  7|  2019-01-01 00:05:08|   6011360759745864|fraud_Corwin-Collins|gas_transport| 71.65|     Steven| Williams|     M|231 Flores Pass S...|            Edinburg|   VA|22824|38.8432|          -78.6003|    6018|Designer, multimedia|1947-08-21|6d294ed2cc447d2c7...|1325376308|         38.948089|        -78.540296|       0|
|  8|  2019-01-01 00:05:18|   4922710831011201|    fraud_Herzog Ltd|     misc_pos|  4.27|    Heather|    Chase|     F|6888 Hicks Stream...|               Manor|   PA|15665|40.3359|          -79.6607|    1472|Public affairs co...|1941-03-07|fc28024ce480f8ef2...|1325376318|         40.351813|        -79.958146|       0|
|  9|  2019-01-01 00:06:01|   2720830304681674|fraud_Schoen, Kup...|  grocery_pos|198.39|    Melissa|  Aguilar|     F|21326 Taylor Squa...|         Clarksville|   TN|37040| 36.522|-87.34899999999999|  151785|         Pathologist|1974-03-28|3b9014ea8fb80bd65...|1325376361|         37.179198|        -87.485381|       0|
| 10|  2019-01-01 00:06:23|      4642894980163|fraud_Rutherford-...|  grocery_pos| 24.74|      Eddie|   Mendez|     M|1831 Faith View S...|            Clarinda|   IA|51632|40.7491|           -95.038|    7297|          IT trainer|1990-07-13|d71c95ab6b7356dd7...|1325376383|40.275890999999994|        -96.011548|       0|
| 11|  2019-01-01 00:06:53|    377234009633447|fraud_Kerluke-Abs...| shopping_net|  7.77|    Theresa|Blackwell|     F|43576 Kristina Is...| Shenandoah Junction|   WV|25442|39.3716|          -77.8229|    1925|   Systems developer|1966-02-14|3c74776e558f1499a...|1325376413|         40.103866|        -78.624459|       0|
| 12|  2019-01-01 00:06:56|    180042946491150|   fraud_Lockman Ltd|  grocery_pos| 71.22|    Charles|   Robles|     M|    3337 Lisa Divide|    Saint Petersburg|   FL|33710|27.7898|          -82.7243|  341043|      Engineer, land|1989-02-28|c1d9a7ddb1e34639f...|1325376416|         27.630593|        -82.308891|       0|
| 13|  2019-01-01 00:07:27|   5559857416065248|     fraud_Kiehn Inc|  grocery_pos| 96.29|       Jack|     Hill|     M|5916 Susan Bridge...|             Grenada|   CA|96038|41.6125|         -122.5258|     589|     Systems analyst|1945-12-21|413636e759663f264...|1325376447|          41.65752|       -122.230347|       0|
| 14|  2019-01-01 00:09:03|   3514865930894695|   fraud_Beier-Hyatt| shopping_pos|  7.77|Christopher|Castaneda|     M|1632 Cohen Drive ...|High Rolls Mounta...|   NM|88325|32.9396|         -105.8189|     899|     Naval architect|1967-08-30|8a6293af5ed278dea...|1325376543|         32.863258|       -106.520205|       0|
| 15|  2019-01-01 00:09:20|   6011999606625827|fraud_Schmidt and...| shopping_net|  3.26|     Ronald|   Carson|     M|     870 Rocha Drive|     Harrington Park|   NJ| 7640|40.9918|            -73.98|    4664|Radiographer, dia...|1965-06-30|baae0b096835c9758...|1325376560|         41.831174|        -74.335559|       0|
| 16|  2019-01-01 00:10:49|   6011860238257910|fraud_Lebsack and...|     misc_net| 327.0|       Lisa|   Mendez|     F|44259 Beth Statio...|              Lahoma|   OK|73754| 36.385|          -98.0727|    1078|Programme researc...|1952-07-06|991c04803b4d4eeab...|1325376649|36.384091999999995|        -99.048472|       0|
| 17|  2019-01-01 00:10:58|   3565423334076143|  fraud_Mayert Group| shopping_pos|341.67|     Nathan|   Thomas|     M|4923 Campbell Pin...|            Carlisle|   IN|47838|38.9763|          -87.3667|    4081|     Energy engineer|1938-03-15|f12cf52be2175703d...|1325376658|38.674490999999996|        -88.305767|       0|
| 18|  2019-01-01 00:11:14|   2348245054386329|fraud_Konopelski,...|  food_dining| 63.07|     Justin|      Gay|     M|268 Hayes Rue Sui...|         Harborcreek|   PA|16421|42.1767|          -79.9416|    2518|     Event organiser|1946-02-02|8500f3d459047eac8...|1325376674|         41.430274|        -79.492553|       0|
| 19|  2019-01-01 00:12:34|4956828990005111019|fraud_Schultz, Si...|  grocery_pos| 44.71|    Kenneth| Robinson|     M|  269 Sanchez Rapids|           Elizabeth|   NJ| 7208|40.6747|          -74.2239|  124967|Operational resea...|1980-12-21|09eff9c806365e2a6...|1325376754|         40.079588|-74.84808699999999|       0|
+---+---------------------+-------------------+--------------------+-------------+------+-----------+---------+------+--------------------+--------------------+-----+-----+-------+------------------+--------+--------------------+----------+--------------------+----------+------------------+------------------+--------+
only showing top 20 rows

In [4]:
from pyspark import SparkFiles
url ="https://fraudcreditcard.s3.amazonaws.com/fraudTest.csv"
spark.sparkContext.addFile(url)
df = spark.read.csv(SparkFiles.get("fraudTest.csv"), sep=",", header=True)
# Show DataFrame
df.show()

+---+---------------------+-----------+--------------------+--------------+------+---------+--------+------+--------------------+-------------+-----+-----+-------+---------+--------+--------------------+----------+--------------------+----------+---------+-----------+--------+
|_c0|trans_date_trans_time|     cc_num|            merchant|      category|   amt|    first|    last|gender|              street|         city|state|  zip|    lat|     long|city_pop|                 job|       dob|           trans_num| unix_time|merch_lat| merch_long|is_fraud|
+---+---------------------+-----------+--------------------+--------------+------+---------+--------+------+--------------------+-------------+-----+-----+-------+---------+--------+--------------------+----------+--------------------+----------+---------+-----------+--------+
|  0|      6/21/2020 12:14|2.29116E+15|fraud_Kirlin and ...| personal_care|  2.86|     Jeff| Elliott|     M|   351 Darlene Green|     Columbia|   SC|29209|33.9659| -80.9355|  333497| Mechanical engineer| 3/19/1968|2da90c7d74bd46a0c...|1371816865|33.986391| -81.200714|       0|
|  1|      6/21/2020 12:14|3.57303E+15|fraud_Sporer-Keebler| personal_care| 29.84|   Joanne|Williams|     F|    3638 Marsh Union|      Altonah|   UT|84002|40.3207| -110.436|     302|Sales professiona...| 1/17/1990|324cc204407e99f51...|1371816873|39.450498|-109.960431|       0|
|  2|      6/21/2020 12:14|3.59822E+15|fraud_Swaniawski,...|health_fitness| 41.28|   Ashley|   Lopez|     F|9333 Valentine Point|     Bellmore|   NY|11710|40.6729| -73.5365|   34496|   Librarian, public|10/21/1970|c81755dbbbea9d5c7...|1371816893| 40.49581| -74.196111|       0|
|  3|      6/21/2020 12:15|3.59192E+15|   fraud_Haley Group|      misc_pos| 60.05|    Brian|Williams|     M|32941 Krystal Mil...|   Titusville|   FL|32780|28.5697| -80.8191|   54767|        Set designer| 7/25/1987|2159175b9efe66dc3...|1371816915|28.812398| -80.883061|       0|
|  4|      6/21/2020 12:15|3.52683E+15|fraud_Johnston-Ca...|        travel|  3.19|   Nathan|  Massey|     M|5783 Evan Roads A...|     Falmouth|   MI|49632|44.2529|  -85.017|    1126|  Furniture designer|  7/6/1955|57ff021bd3f328f87...|1371816917|44.959148| -85.884734|       0|
|  5|      6/21/2020 12:15|3.04077E+13| fraud_Daugherty LLC|     kids_pets| 19.55| Danielle|   Evans|     F|76752 David Lodge...|    Breesport|   NY|14816|42.1939| -76.7361|     520|     Psychotherapist|10/13/1991|798db04aaceb4febd...|1371816937|41.747157| -77.584197|       0|
|  6|      6/21/2020 12:15|2.13181E+14| fraud_Romaguera Ltd|health_fitness|133.93|    Kayla|  Sutton|     F|     010 Weaver Land|     Carlotta|   CA|95528| 40.507|-123.9743|    1139|Therapist, occupa...| 1/15/1951|17003d7ce534440ea...|1371816944|41.499458|-124.888729|       0|
|  7|      6/21/2020 12:15|3.58929E+15|   fraud_Reichel LLC| personal_care| 10.37|    Paula| Estrada|     F|     350 Stacy Glens|      Spencer|   SD|57374|43.7557| -97.5936|     343|Development worke...|  3/5/1972|8be473af4f05fc614...|1371816950|44.495498| -97.728453|       0|
|  8|      6/21/2020 12:16|3.59636E+15|fraud_Goyette, Ho...|  shopping_pos|  4.37|    David| Everett|     M|     4138 David Fall|   Morrisdale|   PA|16858|41.0001| -78.2357|    3688|       Advice worker| 5/27/1973|71a1da150d1ce5101...|1371816970|41.546067| -78.120238|       0|
|  9|      6/21/2020 12:16| 3.5469E+15| fraud_Kilback Group|   food_dining| 66.54|    Kayla|  Obrien|     F|7921 Robert Port ...| Prairie Hill|   TX|76678|31.6591| -96.8094|     263|           Barrister| 5/30/1956|a7915132c7c424099...|1371816971|31.782919| -96.366185|       0|
| 10|      6/21/2020 12:16|2.24254E+15|fraud_Feil, Hilpe...|   food_dining|  7.01|   Samuel| Jenkins|     M|43235 Mckenzie Vi...|     Westport|   KY|40077|38.4921| -85.4524|     564| Pensions consultant| 4/10/1996|3b8e4d02d9e1a3bf9...|1371816980|38.977546| -84.727994|       0|
| 11|      6/21/2020 12:16|5.71465E+11|fraud_Gottlieb Group|     kids_pets|  42.4|    Louis|  Fisher|     M|     45654 Hess Rest|Fort Washakie|   WY|82514|43.0048|-108.8964|    1645|   Freight forwarder| 2/26/1976|fa3071565d94fb286...|1371817007|42.687774|-108.670054|       0|
| 12|      6/21/2020 12:17|6.59325E+15|fraud_Connelly-Ca...|          home|  2.91|  Melissa|    Meza|     F|  244 Abbott Parkway|  Loxahatchee|   FL|33470|26.7383|  -80.276|   26551|           Paramedic|  1/4/1977|a21cb82e7d8fdbf40...|1371817041| 26.07846| -80.569932|       0|
| 13|      6/21/2020 12:18| 4.9883E+12|fraud_Bechtelar-R...|   food_dining|  7.93|  William|Thompson|     M|977 Rita Grove Ap...|  Rock Tavern|   NY|12575|41.4575| -74.1659|    2258|   Building surveyor| 3/17/1937|d0d2b5cca5ae19e0a...|1371817107| 40.71168| -73.668384|       0|
| 14|      6/21/2020 12:18| 6.0115E+15|fraud_Lubowitz-Wa...|     kids_pets|  2.91|   Ashley| Whitney|     F|   4038 Smith Avenue|        Jones|   AL|36749|32.5104| -86.8138|    1089|  Materials engineer| 11/2/1971|61dca41a9728ea5fd...|1371817117|32.721131| -87.253846|       0|
| 15|      6/21/2020 12:18|4.57064E+15|fraud_Welch, Rath...| entertainment| 24.73|Christine| Leblanc|     F|5097 Jodi Vista S...|      Deltona|   FL|32725|28.8989| -81.2473|   88735|Commercial hortic...|  4/9/1988|ea11379e8aa1b08d5...|1371817121| 29.83155| -80.926829|       0|
| 16|      6/21/2020 12:18|4.90663E+18|  fraud_Hickle Group|  shopping_pos|  2.33|  Charles|  Moreno|     M|838 Franklin Prai...|     Key West|   FL|33040|24.6557| -81.3824|   32891|        Town planner| 2/13/1987|00da72495351ce6bd...|1371817134|24.306325| -81.065169|       0|
| 17|      6/21/2020 12:19|4.90885E+15|fraud_Lang, Towne...|     kids_pets|  16.6|   Lauren|  Torres|     F|   03030 White Lakes|    Grandview|   TX|76050|32.2779| -97.2351|    5875|Radiographer, the...| 7/24/1992|67288141e8206f6f4...|1371817190|33.182349| -97.919284|       0|
| 18|      6/21/2020 12:19|4.86131E+18|fraud_Morissette LLC| entertainment| 80.11|   Ashley|    Cruz|     F|65417 Walsh Radia...|  Saint Amant|   LA|70774|30.2385| -90.8435|   10076|Surveyor, rural p...|12/16/1977|71bb6ee81f9af4d2a...|1371817196| 30.44999| -89.930996|       0|
| 19|      6/21/2020 12:20|6.53844E+15|  fraud_Prosacco LLC| personal_care|  5.71|     Gina|  Grimes|     F|     444 Robert Mews| Clarks Mills|   PA|16114|41.3851| -80.1752|     606|      Energy manager| 9/22/1997|2d7640ea4f3bcd520...|1371817213|40.508064| -79.615158|       0|
+---+---------------------+-----------+--------------------+--------------+------+---------+--------+------+--------------------+-------------+-----+-----+-------+---------+--------+--------------------+----------+--------------------+----------+---------+-----------+--------+
only showing top 20 rows

In [5]:
# importing the packages
import datetime
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
from datetime import date
import sklearn.exceptions
from pylab import rcParams
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.svm import OneClassSVM
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import IsolationForest
from imblearn.under_sampling import NearMiss 
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import LocalOutlierFactor
from sklearn.metrics import plot_confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn import datasets, metrics, preprocessing, svm
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import classification_report,accuracy_score
warnings.filterwarnings("ignore", category=sklearn.exceptions.UndefinedMetricWarning)
from imblearn.metrics import classification_report_imbalanced


from sklearn.ensemble import RandomForestClassifier

In [6]:
# loading data
data_train = pd.read_csv("https://fraudcreditcard.s3.amazonaws.com/fraudTrain.csv")
data_test = pd.read_csv("https://fraudcreditcard.s3.amazonaws.com/fraudTest.csv")

In [7]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

In [8]:
data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             555719 non-null  int64
 1   trans_date_trans_time  555719 non-null  object
 2   cc_num                 555719 non-null  float64
 3   merchant               555719 non-null  object
 4   category               555719 non-null  object
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  object
 7   last                   555719 non-null  object
 8   gender                 555719 non-null  object
 9   street                 555719 non-null  object
 10  city                   555719 non-null  object
 11  state                  555719 non-null  object
 12  zip                    555719 non-null  int64
 13  lat                    555719 non-null  float64
 14  long                   555719 non-null  float64
 15  city_pop               555719 non-null  int64
 16  job                    555719 non-null  object
 17  dob                    555719 non-null  object
 18  trans_num              555719 non-null  object
 19  unix_time              555719 non-null  int64
 20  merch_lat              555719 non-null  float64
 21  merch_long             555719 non-null  float64
 22  is_fraud               555719 non-null  int64
dtypes: float64(6), int64(5), object(12)
memory usage: 97.5+ MB

In [9]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

In [10]:
print(data_train.shape,data_test.shape)

(1296675, 23) (555719, 23)

In [11]:
# taking smaller sample to run the model faster

df_train= data_train.sample(frac = 0.1,random_state=1)
df_test= data_test.sample(frac = 0.05,random_state=1)
print(df_train.shape,df_test.shape)
df_train.head(10)

(129668, 23) (27786, 23)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
94102,94102,2019-02-25 08:24:40,374497717543058,fraud_Funk Group,grocery_net,20.00,Linda,Hurst,F,31701 Tucker Square Suite 893,...,47.1709,-100.7944,1190,"Designer, ceramics/pottery",1948-06-30,1595dec12f6f19ceaae9b7df0f8af5c0,1330158280,46.398331,-99.813959,0
198791,198791,2019-04-12 19:50:15,4428154703770710,"fraud_Prosacco, Kreiger and Kovacek",home,284.88,Brittany,Guerra,F,79209 Gary Dale,...,46.5901,-117.1692,761,Chief Marketing Officer,1943-06-30,0ed26b649ed0fce94d8e632b7208dea0,1334260215,45.687331,-117.488135,0
1238587,1238587,2020-05-31 21:50:53,213148039875802,"fraud_Langworth, Boehm and Gulgowski",shopping_net,5.07,Jill,Jacobs,F,034 Kimberly Mountains,...,27.9551,-82.2966,79613,Environmental consultant,1978-11-30,7096316ec1a4b261e8613013827abae7,1370037053,27.254081,-81.974799,0
619078,619078,2019-09-20 17:06:52,2283743876903625,fraud_Conroy-Emard,food_dining,45.38,Shannon,Williams,F,9345 Spencer Junctions Suite 183,...,34.0770,-84.3033,165556,Prison officer,1997-12-27,d02c35d7bda19c3da84b6d01f02da7e8,1348160812,34.551957,-83.374265,0
573850,573850,2019-08-31 23:22:50,4798937978667559470,fraud_Adams-Barrows,health_fitness,27.52,Robert,Williams,M,09419 Lewis Rapids,...,43.6088,-83.9530,67858,Water quality scientist,1995-03-13,dccf059d9fdc15f1fb9d2abb50e7314b,1346455370,43.032957,-83.521294,0
1201872,1201872,2020-05-17 18:21:17,6538891242532018,fraud_Effertz LLC,entertainment,131.75,Jodi,Rodriguez,F,5796 Lee Coves Apt. 286,...,36.0244,-90.9288,7155,"Engineer, control and instrumentation",1977-03-23,4e700b0737fbfe948c3af0af594a964e,1368814877,35.068173,-90.274482,0
61984,61984,2019-02-05 21:47:54,4998109455173950,fraud_Morissette LLC,entertainment,146.69,Mary,Pruitt,F,2819 Luke Greens Suite 563,...,38.9621,-94.5959,545147,Counsellor,1987-11-18,dd7ea05d67a0ff509e3d0fb1fdfe7f38,1328478474,38.229734,-94.197224,0
552029,552029,2019-08-24 11:59:19,60422928733,fraud_Wiegand-Lowe,grocery_net,74.27,Jeffrey,Powers,M,38352 Parrish Road Apt. 652,...,33.6028,-81.9748,46944,Secondary school teacher,1942-04-02,214d540bdca14cdeb5eb347784d44f0c,1345809559,34.230048,-82.674878,0
1079425,1079425,2020-03-24 06:07:24,377264520876399,fraud_Harris Group,food_dining,11.22,Kara,Miles,F,2076 Thomas Roads Suite 970,...,34.3424,-80.5000,4424,Lawyer,1961-07-31,e7370494e1d3171f0ce1a5bdbae071f4,1364105244,33.700800,-80.342778,0
681734,681734,2019-10-18 03:41:04,4070511711385545,fraud_Dach-Nader,misc_net,3.96,Stephanie,Hopkins,F,44089 Carrie Crossing Suite 954,...,28.9814,-98.0156,2435,"Engineer, mining",1967-04-09,e2f08d1f890af7c6f4d3dfb6cc90a18a,1350531664,29.905143,-98.185725,0

In [12]:
df_train.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [13]:
data_test.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

Data Cleaning

In [14]:
# function to drop tbe columns
def dropCol(data):
    col_to_drop = ['trans_date_trans_time','Unnamed: 0','cc_num','first','last','trans_num']
    res = data.drop(col_to_drop,axis = 1)
    return res

In [15]:
# dropping the columns
# dropping the columns ['trans_date_trans_time','Unnamed: 0','cc_num','first','last','trans_num']
# train data set
df_train = dropCol(df_train)
# test data set
df_test = dropCol(df_test)

print ( df_train.shape, df_test.shape)

(129668, 17) (27786, 17)

In [16]:
# function to convert dob to years
def age_years(born):
    return 2022 - int(born[0:4])

# replacing the dob column with age column in our data set for test and train
df_train['age'] = df_train['dob'].apply(lambda x: age_years(x))

In [17]:
df_train

,merchant,category,amt,gender,street,city,state,zip,lat,long,city_pop,job,dob,unix_time,merch_lat,merch_long,is_fraud,age
94102,fraud_Funk Group,grocery_net,20.00,F,31701 Tucker Square Suite 893,Wilton,ND,58579,47.1709,-100.7944,1190,"Designer, ceramics/pottery",1948-06-30,1330158280,46.398331,-99.813959,0,74
198791,"fraud_Prosacco, Kreiger and Kovacek",home,284.88,F,79209 Gary Dale,Colton,WA,99113,46.5901,-117.1692,761,Chief Marketing Officer,1943-06-30,1334260215,45.687331,-117.488135,0,79
1238587,"fraud_Langworth, Boehm and Gulgowski",shopping_net,5.07,F,034 Kimberly Mountains,Brandon,FL,33510,27.9551,-82.2966,79613,Environmental consultant,1978-11-30,1370037053,27.254081,-81.974799,0,44
619078,fraud_Conroy-Emard,food_dining,45.38,F,9345 Spencer Junctions Suite 183,Alpharetta,GA,30009,34.0770,-84.3033,165556,Prison officer,1997-12-27,1348160812,34.551957,-83.374265,0,25
573850,fraud_Adams-Barrows,health_fitness,27.52,M,09419 Lewis Rapids,Bay City,MI,48706,43.6088,-83.9530,67858,Water quality scientist,1995-03-13,1346455370,43.032957,-83.521294,0,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944454,fraud_Reichert-Weissnat,travel,5.83,F,6911 Nicholas Keys Apt. 237,Armagh,PA,15920,40.4603,-79.0097,922,Early years teacher,1972-10-04,1358007774,40.522369,-79.314668,0,50
23683,"fraud_Baumbach, Strosin and Nicolas",shopping_pos,1.96,F,27479 Reeves Dale,Whaleyville,MD,21872,38.4121,-75.2811,718,Regulatory affairs officer,1985-03-19,1326572609,38.534192,-76.161654,0,37
296375,fraud_Lubowitz-Walter,kids_pets,26.59,F,72966 Shannon Pass Apt. 391,Bauxite,AR,72011,34.5091,-92.4828,4074,"Scientist, audiological",1975-12-20,1337963080,35.175647,-91.740062,0,47
306312,"fraud_Runolfsdottir, Mueller and Hand",entertainment,6.00,M,3283 James Station,Fayetteville,NC,28314,35.0583,-79.0080,238602,"Scientist, research (maths)",1993-05-14,1338216727,34.360264,-78.128199,0,29
1171139,"fraud_Boehm, Predovic and Reinger",misc_pos,44.70,M,8415 Vaughn Squares Apt. 788,Acworth,NH,3601,43.1960,-72.3001,477,Naval architect,1988-04-15,1367637527,44.156195,-73.285582,0,34

In [18]:
# function to convert dob to years
from datetime import datetime
def age(born):
    born = datetime.strptime(born, "%m/%d/%Y").date()
    today = date.today()
    return today.year - born.year - ((today.month, 
                                      today.day) < (born.month, 
                                                    born.day))

# replacing the dob column with age column in our data set for test and train
df_test['age'] = df_test['dob'].apply(age)

In [19]:
df_test

,merchant,category,amt,gender,street,city,state,zip,lat,long,city_pop,job,dob,unix_time,merch_lat,merch_long,is_fraud,age
207181,fraud_Bernier and Sons,kids_pets,41.17,M,7838 Jason Squares,Elizabethtown,KY,42701,37.6848,-85.8784,48194,Surgeon,5/3/1990,1378054835,38.370429,-86.671765,0,31
501018,fraud_McCullough LLC,misc_pos,51.89,M,27718 Mason Bypass,Mount Saint Joseph,OH,45051,39.0965,-84.6431,177,Exhibition designer,5/30/1974,1387521110,39.090859,-84.115650,0,47
312515,fraud_Durgan-Auer,misc_net,2.22,F,0665 Lisa Alley,Winger,MN,56592,47.5375,-95.9941,516,Applications developer,6/7/1966,1382090733,47.285136,-96.180797,0,55
407433,fraud_Berge LLC,gas_transport,87.21,M,1198 Robert Stravenue Apt. 479,Armonk,NY,10504,41.1360,-73.7009,7987,Television/film/video producer,3/16/1964,1385702190,41.503596,-73.220229,0,58
386454,"fraud_Johnson, Runolfsdottir and Mayer",misc_net,79.78,F,6412 Elizabeth Gardens Suite 633,Maysville,KY,41056,38.6207,-83.8067,14228,Advertising account executive,3/26/1971,1384849723,39.043199,-83.842076,0,51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259031,fraud_Bernier and Sons,kids_pets,44.60,F,47035 Murray Harbors,Achille,OK,74720,33.8396,-96.3648,608,Seismic interpreter,5/27/1993,1380029778,34.417174,-95.604504,0,28
438676,fraud_Kertzmann LLC,health_fitness,11.18,F,2870 Bean Terrace Apt. 756,Thomas,WV,26292,39.1505,-79.5030,836,Forensic psychologist,8/29/1981,1386336792,38.498314,-80.141704,0,40
97265,"fraud_Cremin, Hamill and Reichel",misc_pos,2.06,F,3861 Anderson Ramp Apt. 536,Drakes Branch,VA,23937,36.9688,-78.5615,1970,Energy engineer,9/2/1985,1374759332,36.542796,-79.299846,0,36
117755,fraud_Wilkinson LLC,personal_care,174.97,F,334 Adam Mountains Apt. 868,Manquin,VA,23106,37.7184,-77.1860,976,"Engineer, automotive",6/19/1999,1375388423,38.584513,-76.880740,0,22
256452,fraud_Pollich LLC,home,19.26,F,759 Erin Mount Suite 956,May,TX,76857,31.9571,-98.9656,1791,Corporate investment banker,7/26/1965,1379888205,31.357776,-98.058280,0,56

In [20]:
df_train = df_train.drop(['dob'],axis =1)
df_train

,merchant,category,amt,gender,street,city,state,zip,lat,long,city_pop,job,unix_time,merch_lat,merch_long,is_fraud,age
94102,fraud_Funk Group,grocery_net,20.00,F,31701 Tucker Square Suite 893,Wilton,ND,58579,47.1709,-100.7944,1190,"Designer, ceramics/pottery",1330158280,46.398331,-99.813959,0,74
198791,"fraud_Prosacco, Kreiger and Kovacek",home,284.88,F,79209 Gary Dale,Colton,WA,99113,46.5901,-117.1692,761,Chief Marketing Officer,1334260215,45.687331,-117.488135,0,79
1238587,"fraud_Langworth, Boehm and Gulgowski",shopping_net,5.07,F,034 Kimberly Mountains,Brandon,FL,33510,27.9551,-82.2966,79613,Environmental consultant,1370037053,27.254081,-81.974799,0,44
619078,fraud_Conroy-Emard,food_dining,45.38,F,9345 Spencer Junctions Suite 183,Alpharetta,GA,30009,34.0770,-84.3033,165556,Prison officer,1348160812,34.551957,-83.374265,0,25
573850,fraud_Adams-Barrows,health_fitness,27.52,M,09419 Lewis Rapids,Bay City,MI,48706,43.6088,-83.9530,67858,Water quality scientist,1346455370,43.032957,-83.521294,0,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944454,fraud_Reichert-Weissnat,travel,5.83,F,6911 Nicholas Keys Apt. 237,Armagh,PA,15920,40.4603,-79.0097,922,Early years teacher,1358007774,40.522369,-79.314668,0,50
23683,"fraud_Baumbach, Strosin and Nicolas",shopping_pos,1.96,F,27479 Reeves Dale,Whaleyville,MD,21872,38.4121,-75.2811,718,Regulatory affairs officer,1326572609,38.534192,-76.161654,0,37
296375,fraud_Lubowitz-Walter,kids_pets,26.59,F,72966 Shannon Pass Apt. 391,Bauxite,AR,72011,34.5091,-92.4828,4074,"Scientist, audiological",1337963080,35.175647,-91.740062,0,47
306312,"fraud_Runolfsdottir, Mueller and Hand",entertainment,6.00,M,3283 James Station,Fayetteville,NC,28314,35.0583,-79.0080,238602,"Scientist, research (maths)",1338216727,34.360264,-78.128199,0,29
1171139,"fraud_Boehm, Predovic and Reinger",misc_pos,44.70,M,8415 Vaughn Squares Apt. 788,Acworth,NH,3601,43.1960,-72.3001,477,Naval architect,1367637527,44.156195,-73.285582,0,34

In [21]:
df_test = df_test.drop(['dob'],axis =1)
df_test

,merchant,category,amt,gender,street,city,state,zip,lat,long,city_pop,job,unix_time,merch_lat,merch_long,is_fraud,age
207181,fraud_Bernier and Sons,kids_pets,41.17,M,7838 Jason Squares,Elizabethtown,KY,42701,37.6848,-85.8784,48194,Surgeon,1378054835,38.370429,-86.671765,0,31
501018,fraud_McCullough LLC,misc_pos,51.89,M,27718 Mason Bypass,Mount Saint Joseph,OH,45051,39.0965,-84.6431,177,Exhibition designer,1387521110,39.090859,-84.115650,0,47
312515,fraud_Durgan-Auer,misc_net,2.22,F,0665 Lisa Alley,Winger,MN,56592,47.5375,-95.9941,516,Applications developer,1382090733,47.285136,-96.180797,0,55
407433,fraud_Berge LLC,gas_transport,87.21,M,1198 Robert Stravenue Apt. 479,Armonk,NY,10504,41.1360,-73.7009,7987,Television/film/video producer,1385702190,41.503596,-73.220229,0,58
386454,"fraud_Johnson, Runolfsdottir and Mayer",misc_net,79.78,F,6412 Elizabeth Gardens Suite 633,Maysville,KY,41056,38.6207,-83.8067,14228,Advertising account executive,1384849723,39.043199,-83.842076,0,51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259031,fraud_Bernier and Sons,kids_pets,44.60,F,47035 Murray Harbors,Achille,OK,74720,33.8396,-96.3648,608,Seismic interpreter,1380029778,34.417174,-95.604504,0,28
438676,fraud_Kertzmann LLC,health_fitness,11.18,F,2870 Bean Terrace Apt. 756,Thomas,WV,26292,39.1505,-79.5030,836,Forensic psychologist,1386336792,38.498314,-80.141704,0,40
97265,"fraud_Cremin, Hamill and Reichel",misc_pos,2.06,F,3861 Anderson Ramp Apt. 536,Drakes Branch,VA,23937,36.9688,-78.5615,1970,Energy engineer,1374759332,36.542796,-79.299846,0,36
117755,fraud_Wilkinson LLC,personal_care,174.97,F,334 Adam Mountains Apt. 868,Manquin,VA,23106,37.7184,-77.1860,976,"Engineer, automotive",1375388423,38.584513,-76.880740,0,22
256452,fraud_Pollich LLC,home,19.26,F,759 Erin Mount Suite 956,May,TX,76857,31.9571,-98.9656,1791,Corporate investment banker,1379888205,31.357776,-98.058280,0,56

In [22]:
data_train.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [23]:
# function to convert dob to years
def age_years(born):
    return 2022 - int(born[0:4])

# replacing the dob column with age column in our data set for test and train
data_train['age'] = data_train['dob'].apply(lambda x: age_years(x))

In [24]:
data_train.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,age
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,34
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,44
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,60
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,55
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,36

In [25]:
clean_train = data_train[['merchant', 'category', 'amt', 'gender', 'unix_time', 'merch_lat', 'merch_long', 'is_fraud', 'age']]
clean_train.head()

,merchant,category,amt,gender,unix_time,merch_lat,merch_long,is_fraud,age
0,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,1325376018,36.011293,-82.048315,0,34
1,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,1325376044,49.159047,-118.186462,0,44
2,fraud_Lind-Buckridge,entertainment,220.11,M,1325376051,43.150704,-112.154481,0,60
3,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,1325376076,47.034331,-112.561071,0,55
4,fraud_Keeling-Crist,misc_pos,41.96,M,1325376186,38.674999,-78.632459,0,36

In [27]:
clean_df = pd.read_csv("https://fraudcreditcard.s3.amazonaws.com/clean_data_train.csv")

In [28]:
clean_df.head()

,merchant,category,amt,gender,unix_time,merch_lat,merch_long,is_fraud,age
0,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,1325376018,36.011293,-82.048315,0,34
1,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,1325376044,49.159047,-118.186462,0,44
2,fraud_Lind-Buckridge,entertainment,220.11,M,1325376051,43.150704,-112.154481,0,60
3,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,1325376076,47.034331,-112.561071,0,55
4,fraud_Keeling-Crist,misc_pos,41.96,M,1325376186,38.674999,-78.632459,0,36

Machine Learning :
BalancedRandomForestClassifier

In [29]:
# Create our features
X = pd.get_dummies(df_train, columns=['merchant', 'category', 'gender', 'street', 
                'city', 'state', 'job'])

# Create our target
y = df_train['is_fraud']

In [30]:
X.describe()

,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud,age,...,job_Video editor,job_Visual merchandiser,job_Volunteer coordinator,job_Warden/ranger,job_Waste management officer,job_Water engineer,job_Water quality scientist,job_Web designer,job_Wellsite geologist,job_Writer
count,129668.000000,129668.000000,129668.000000,129668.000000,1.296680e+05,1.296680e+05,129668.000000,129668.000000,129668.000000,129668.000000,...,129668.000000,129668.000000,129668.000000,129668.000000,129668.000000,129668.000000,129668.000000,129668.000000,129668.000000,129668.000000
mean,70.061919,48769.624564,38.531795,-90.195962,8.856453e+04,1.349218e+09,38.532677,-90.195662,0.005437,48.721990,...,0.002560,0.000794,0.001697,0.002537,0.001967,0.004866,0.000370,0.002059,0.002159,0.000386
std,153.627239,26914.806946,5.062368,13.747697,3.015705e+05,1.279134e+07,5.094736,13.758655,0.073535,17.374394,...,0.050536,0.028173,0.041155,0.050307,0.044302,0.069589,0.019236,0.045331,0.046419,0.019633
min,1.000000,1257.000000,20.027100,-165.672300,2.300000e+01,1.325376e+09,19.035472,-166.657834,0.000000,17.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9.630000,26041.000000,34.668900,-96.798000,7.410000e+02,1.338757e+09,34.751272,-96.899931,0.000000,35.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,47.360000,48174.000000,39.346500,-87.458100,2.456000e+03,1.349244e+09,39.360173,-87.408320,0.000000,47.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,82.940000,72042.000000,41.846700,-80.158000,2.032800e+04,1.359235e+09,41.938529,-80.190236,0.000000,60.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,17897.240000,99783.000000,65.689900,-67.950300,2.906700e+06,1.371817e+09,66.645176,-66.963975,1.000000,98.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [31]:
# Import dependencies
from imblearn.ensemble import BalancedRandomForestClassifier
from sklearn.metrics import balanced_accuracy_score
from imblearn.ensemble import EasyEnsembleClassifier

In [32]:
# Resample the training data with the BalancedRandomForestClassifier

rf_model = BalancedRandomForestClassifier(n_estimators=100, random_state=1)
rf_model = rf_model.fit(X,y)
print(rf_model)

BalancedRandomForestClassifier(random_state=1)

In [33]:
# Calculated the balanced accuracy score
y_pred = rf_model.predict(X)
balanced_accuracy_score(y, y_pred)

0.999740235571443

In [34]:
# Display the confusion matrix
# Calculating the confusion matrix.
y_pred = rf_model.predict(X)
cm = confusion_matrix(y, y_pred)

cm_df = pd.DataFrame(
    cm, index=["Actual high_risk", "Actual low_risk"],
    columns=["Predicted high_risk", "Predicted low_risk"]
)

# Displaying results
display(cm_df)

                  Predicted high_risk  Predicted low_risk
Actual high_risk               128896                  67
Actual low_risk                     0                 705

In [35]:
# Print the imbalanced classification report

print(classification_report_imbalanced(y, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      1.00      1.00      1.00      1.00    128963
          1       0.91      1.00      1.00      0.95      1.00      1.00       705

avg / total       1.00      1.00      1.00      1.00      1.00      1.00    129668

In [36]:
# List the features sorted in descending order by feature importance
feature_importances = sorted(zip(rf_model.feature_importances_, X.columns), reverse = True)
feature_importances

[(0.36632722096706205, 'is_fraud'),
 (0.17849727494913012, 'amt'),
 (0.016520400651017123, 'unix_time'),
 (0.015287875888139903, 'category_shopping_net'),
 (0.014540104738150414, 'merch_lat'),
 (0.014145734039393986, 'merch_long'),
 (0.012055550690079391, 'lat'),
 (0.011571565941805083, 'long'),
 (0.011396611493750645, 'age'),
 (0.01075946242636187, 'city_pop'),
 (0.009442756548816761, 'zip'),
 (0.009299556040330094, 'category_misc_net'),
 (0.0065404388288600734, 'category_grocery_pos'),
 (0.006177936461648049, 'category_health_fitness'),
 (0.005074823637721482, 'category_gas_transport'),
 (0.004247367515965853, 'category_personal_care'),
 (0.004094068251374308, 'category_kids_pets'),
 (0.003854833638695664, 'category_home'),
 (0.0034935207265959257, 'category_food_dining'),
 (0.0030652932660021233, 'category_misc_pos'),
 (0.002895395540637625, 'gender_F'),
 (0.0022949466430028016, 'gender_M'),
 (0.0022248819543940444, 'category_travel'),
 (0.0020004303713323087, 'category_grocery_net'),
 (0.001893522804716363, 'category_entertainment'),
 (0.0017417068264748397, 'category_shopping_pos'),
 (0.0011113904229516196, 'state_NY'),
 (0.001020324577967005, 'state_PA'),
 (0.000997296880359583, 'state_OH'),
 (0.0009791997259718148, 'state_NE'),
 (0.000978345671509729, 'state_VA'),
 (0.0009124189311020107, 'state_OK'),
 (0.0008934241700229477, 'state_TX'),
 (0.0008798505783586503, 'state_MI'),
 (0.0008594233231390152, 'state_NJ'),
 (0.0008484450423567453, 'state_MN'),
 (0.0008379389677330221, 'state_MO'),
 (0.0008003992307763927, 'merchant_fraud_Abbott-Steuber'),
 (0.0007702872631078039, 'state_CA'),
 (0.0007681540916020097, 'state_TN'),
 (0.0007581509830824555, 'street_25961 Beverly Union Apt. 042'),
 (0.0007505412535666675, 'merchant_fraud_Cormier LLC'),
 (0.000748806580659742, 'state_SC'),
 (0.0007485143222099374, 'merchant_fraud_Kilback LLC'),
 (0.00074607617250072, 'job_Building surveyor'),
 (0.0007357730780508764, 'state_KS'),
 (0.0007256117847083009, 'state_KY'),
 (0.0007152174654149228, 'job_Podiatrist'),
 (0.0006983512260541727, 'state_IL'),
 (0.0006947162273501492, 'street_979 Stewart Lake'),
 (0.0006892396931678438, 'state_AR'),
 (0.0006695199154446292, 'state_WI'),
 (0.0006339852632982378, 'city_Rock Springs'),
 (0.0006331596295341611, 'state_FL'),
 (0.0006196900804528907, 'state_GA'),
 (0.0006048042301780842, 'job_Audiological scientist'),
 (0.0005915859117424937, 'job_Private music teacher'),
 (0.000586485765891081, 'state_NC'),
 (0.000586457715360441, 'state_IN'),
 (0.0005810767276486886, 'job_Dispensing optician'),
 (0.0005601289784528638, 'street_411 Laurie Fords'),
 (0.000537700140102969, 'job_Land/geomatics surveyor'),
 (0.0005375096079333155, 'job_Communications engineer'),
 (0.0005373083816061889, 'merchant_fraud_Kris-Weimann'),
 (0.0005345054714024873, 'merchant_fraud_Herman, Treutel and Dickens'),
 (0.0005333009607854658, 'city_Clarksville'),
 (0.0005329984453669649, 'city_Basye'),
 (0.0005310914827383303, 'job_Designer, ceramics/pottery'),
 (0.000528376937933175, 'merchant_fraud_Mosciski Group'),
 (0.0005259616347077444, 'state_IA'),
 (0.0005112693923844545, 'merchant_fraud_Block Group'),
 (0.000509250399575094, 'merchant_fraud_Goldner, Kovacek and Abbott'),
 (0.0005012527181043295, 'merchant_fraud_Corwin-Collins'),
 (0.0004972137565286861, 'job_Race relations officer'),
 (0.0004969963603431818, 'state_WY'),
 (0.0004948295712331962, 'street_174 Jennifer Meadow Apt. 467'),
 (0.0004921132149144623, 'job_Risk analyst'),
 (0.0004908865812500496, 'city_New Ellenton'),
 (0.0004899185018670995, 'state_LA'),
 (0.0004881159957130222, 'state_MD'),
 (0.0004755049798537377, 'city_Westport'),
 (0.0004745750432693074, 'job_Music therapist'),
 (0.00047189504872214465, 'job_Scientist, audiological'),
 (0.0004698091334398741, 'merchant_fraud_Prohaska-Murray'),
 (0.0004696226666817922, 'state_AL'),
 (0.00045889964274000285,
  'merchant_fraud_Klocko, Runolfsdottir and Breitenberg'),
 (0.00044622656572723576, 'merchant_fraud_Kozey-Boehm'),
 (0.0004343456284929166, 'merchant_fraud_Erdman-Kertzmann'),
 (0.00043399748973546386, 'job_Pensions consultant'),
 (0.00043325109156902385, 'job_Medical technical officer'),
 (0.0004304484532957656, 'job_Engineering geologist'),
 (0.00042806822646682086, 'job_Chartered accountant'),
 (0.0004267150089834528, 'street_81708 Christopher Plaza'),
 (0.0004241230944742522, 'job_Travel agency manager'),
 (0.00042011890874990354, 'street_90662 Lewis Avenue'),
 (0.0004199512177156659, 'city_Altonah'),
 (0.0004191334124466209, 'merchant_fraud_Haag-Blanda'),
 (0.00041868426163546205, 'merchant_fraud_Conroy-Cruickshank'),
 (0.00041370037751333204, 'city_Marshall'),
 (0.0004134078377554305, 'city_North Wilkesboro'),
 (0.00041246426376737586, 'city_Brashear'),
 (0.0004101066805769714, 'city_Gregory'),
 (0.0004076302865211755, 'merchant_fraud_Schaefer Ltd'),
 (0.00040698356002888967, 'street_4529 Cannon Alley'),
 (0.00040671431068008254, 'city_Mountain Park'),
 (0.0004059057635228071, 'job_Secondary school teacher'),
 (0.0004048797388022042, "job_Nurse, children's"),
 (0.0004044723835515811, 'job_Writer'),
 (0.00040182169582139314, 'job_Product/process development scientist'),
 (0.00039599502395452733, 'job_Pharmacist, hospital'),
 (0.0003908156313406853, 'job_Sales professional, IT'),
 (0.0003903753687673561, 'merchant_fraud_Zboncak LLC'),
 (0.0003895542589733722, 'merchant_fraud_Gutmann Ltd'),
 (0.00038929897960596855, 'city_Clayton'),
 (0.00038812221874815817, 'merchant_fraud_Altenwerth, Cartwright and Koss'),
 (0.0003878937745782697, 'street_43235 Mckenzie Views Apt. 837'),
 (0.00038594883814270736, 'merchant_fraud_Brekke and Sons'),
 (0.0003850697678700816, 'job_Emergency planning/management officer'),
 (0.000383918954914748, 'state_CO'),
 (0.00038353215728929006, 'state_VT'),
 (0.0003810212536659344, 'city_Avoca'),
 (0.00038053067862767924, 'street_17547 Stephen Turnpike Apt. 846'),
 (0.0003804888780880911, 'city_Jordanville'),
 (0.0003759007428712773, 'job_Materials engineer'),
 (0.0003753916317968532, 'job_Neurosurgeon'),
 (0.0003718614892416184, 'city_Huslia'),
 (0.0003715556797827523, 'city_North Loup'),
 (0.0003706257841100497, 'job_Agricultural consultant'),
 (0.00037037444346803934, 'job_Financial trader'),
 (0.0003693900244702175, 'state_OR'),
 (0.00036770523362215555,
  'job_Historic buildings inspector/conservation officer'),
 (0.0003633601948967942, "job_Politician's assistant"),
 (0.0003598889618990048, 'street_109 Brian Lights Apt. 504'),
 (0.0003578372680540861, 'merchant_fraud_Gleason-Macejkovic'),
 (0.00035707497111175614, 'state_ME'),
 (0.0003558903444453578, 'state_MT'),
 (0.00035373033885618147, 'street_653 Jessica Extension Apt. 668'),
 (0.00035314168780375727, 'merchant_fraud_Bruen-Yost'),
 (0.0003500816919588471, 'city_Monetta'),
 (0.00035007267800284017, 'city_Centerview'),
 (0.0003491998858810664, 'merchant_fraud_Kuhic, Bins and Pfeffer'),
 (0.00034777028401369035, 'merchant_fraud_Schumm, Bauch and Ondricka'),
 (0.00034392698003555476, 'state_UT'),
 (0.0003416076431274582, 'merchant_fraud_Friesen-Stamm'),
 (0.00033903385234226744, 'merchant_fraud_Kerluke-Abshire'),
 (0.00033747545578156706, 'city_San Diego'),
 (0.00033716114225195305, 'merchant_fraud_Schmidt and Sons'),
 (0.0003371255814098529, 'merchant_fraud_Effertz LLC'),
 (0.0003351908918153902, 'job_Television production assistant'),
 (0.0003347037045297829, 'street_56812 Francis Courts'),
 (0.0003335553201036405, 'job_Biomedical scientist'),
 (0.0003324525936539582, 'street_05050 Rogers Well Apt. 439'),
 (0.0003315553594711852, 'job_Librarian, public'),
 (0.00033008885110884305, 'merchant_fraud_Olson, Becker and Koch'),
 (0.0003296941331376591, 'street_615 Clarke Spring Apt. 172'),
 (0.0003296543575499529, 'state_WV'),
 (0.0003295739300548235, 'city_Moscow'),
 (0.0003295477287758184, 'merchant_fraud_Pouros-Haag'),
 (0.0003294009367695653, 'job_Chemist, analytical'),
 (0.0003281064595500978, 'job_Medical sales representative'),
 (0.0003271063881722582, 'merchant_fraud_Brown Inc'),
 (0.0003258611782485552, 'city_May'),
 (0.0003249703998527147, 'job_Phytotherapist'),
 (0.0003246412647027677, 'job_Engineer, civil (consulting)'),
 (0.00032458324605718134, 'city_Houston'),
 (0.0003231871157528658, 'job_Medical secretary'),
 (0.00032318061062222445, 'job_Comptroller'),
 (0.0003229197436581659, 'job_Energy engineer'),
 (0.00032250112262529473, 'job_Quantity surveyor'),
 (0.0003216650517997765, 'city_Valentine'),
 (0.00032097883677317834, 'street_55363 Aaron Circle Suite 450'),
 (0.0003204396754798939, 'job_Research scientist (life sciences)'),
 (0.0003200624079969784, 'city_Cass'),
 (0.0003199683089550985, 'city_Hannawa Falls'),
 (0.00031971040117156826, 'job_Social researcher'),
 (0.00031958378075491414, 'state_AZ'),
 (0.0003188815523380153, 'merchant_fraud_Bogisich-Weimann'),
 (0.0003188432054673173, 'merchant_fraud_Nicolas, Hills and McGlynn'),
 (0.0003187959166197314, 'job_Trading standards officer'),
 (0.0003186771037844311, 'merchant_fraud_Jenkins, Hauck and Friesen'),
 (0.00031644077779267014, 'street_969 Huerta Path Apt. 270'),
 (0.0003159489917899375, 'merchant_fraud_Schimmel-Olson'),
 (0.00031082347641682255, 'job_Electronics engineer'),
 (0.00031033750885537206, 'job_Paramedic'),
 (0.0003101377081309949, 'street_5560 Arnold Port Suite 880'),
 (0.0003099560692488987, 'job_Network engineer'),
 (0.00030862966143634394, 'job_Film/video editor'),
 (0.0003074766731724748, 'street_250 Benjamin Hill Apt. 026'),
 (0.0003066186082279691, 'street_2161 Blankenship Freeway'),
 (0.0003062840629179469, 'merchant_fraud_Medhurst PLC'),
 (0.000305636285217144, 'merchant_fraud_Ruecker-Mayert'),
 (0.00030501979038360656, 'city_Lawn'),
 (0.0003049659064943958, 'street_155 Gregory Mount Suite 791'),
 (0.00030495100837166813, 'city_Riverview'),
 (0.0003040061157615106, 'job_Chief Technology Officer'),
 (0.0003038610118989341, 'job_Designer, industrial/product'),
 (0.0003030480624634205, 'merchant_fraud_Nader-Heller'),
 (0.0003027673061375778, 'merchant_fraud_Bradtke PLC'),
 (0.000302757965363247, 'merchant_fraud_Hudson-Ratke'),
 (0.0003015380377948136, 'job_Mechanical engineer'),
 (0.00029966974741171343, 'city_Lebanon'),
 (0.00029887866516719664, 'merchant_fraud_Heathcote LLC'),
 (0.0002983057935869104, 'city_O Brien'),
 (0.0002982657851468364, 'merchant_fraud_Kuhn LLC'),
 (0.0002976274053196511, 'merchant_fraud_Schuppe-Schuppe'),
 (0.0002966024189376765, 'street_7915 Dawn Roads Apt. 544'),
 (0.0002965966800125925, 'street_54220 April Union Suite 403'),
 (0.00029334519803069235, 'city_Apison'),
 (0.0002928391531433408, 'job_Engineer, mining'),
 (0.00029273905819065117, 'job_Pathologist'),
 (0.00029251523393271383, 'merchant_fraud_Cummerata-Jones'),
 (0.00029188157003798694, 'street_53142 Katrina Roads Suite 889'),
 (0.0002913409562100006, 'job_Counsellor'),
 (0.00029000475487989065, 'city_Bay City'),
 (0.00028807231587048683, 'job_Further education lecturer'),
 (0.00028797836115466925, 'merchant_fraud_Reichert, Shanahan and Hayes'),
 (0.00028735046710298993, 'merchant_fraud_Huel Ltd'),
 (0.00028615631565902103, 'state_AK'),
 (0.00028595102475936925, 'city_Utica'),
 (0.00028513168166916485, 'street_759 Erin Mount Suite 956'),
 (0.0002850021216913081, 'job_Early years teacher'),
 (0.0002837507078039894, 'merchant_fraud_Koepp-Parker'),
 (0.00028323625151574093, 'state_NM'),
 (0.0002816303583486659, 'state_WA'),
 (0.00028128676556002033, 'merchant_fraud_Roob LLC'),
 (0.0002802500269807287, 'job_Police officer'),
 (0.0002751134631062405, 'merchant_fraud_Marks Inc'),
 (0.00027339930476809923, "merchant_fraud_O'Keefe-Hudson"),
 (0.0002731413399059641, 'job_Information systems manager'),
 (0.0002720826000278627, 'merchant_fraud_Kuhic LLC'),
 (0.00027098511888347496, 'merchant_fraud_Thiel Ltd'),
 (0.0002703257327764279, 'merchant_fraud_Larkin Ltd'),
 (0.00026927961383094813, 'city_Lagrange'),
 (0.0002690914280088601, 'merchant_fraud_Osinski, Ledner and Leuschke'),
 (0.0002686010480075212, 'state_ND'),
 (0.0002672987967576974, 'job_Lexicographer'),
 (0.00026668789915477396, 'job_Logistics and distribution manager'),
 (0.00026571614611827567, 'street_9412 Harris Mews'),
 (0.0002645675655773871, 'state_SD'),
 (0.00026417535946325057, 'job_Chartered public finance accountant'),
 (0.0002638283693592062, 'job_Sports development officer'),
 (0.00026319652609351044, 'city_Nokomis'),
 (0.00026218718621538436, 'merchant_fraud_Eichmann-Russel'),
 (0.0002620316832395001, 'street_8969 Fuentes Station Apt. 291'),
 (0.00026183363327901316, 'street_3703 Benson Wells'),
 (0.00025979373227386895, 'job_Magazine features editor'),
 (0.0002579734835675152, 'city_Prairie Creek'),
 (0.00025743900830060026, 'merchant_fraud_Hackett-Lueilwitz'),
 (0.00025619598498374964, 'merchant_fraud_Streich, Dietrich and Barton'),
 (0.00025421438798362906, 'job_Occupational psychologist'),
 (0.00025406516647005827, 'merchant_fraud_Flatley-Durgan'),
 (0.00025245637798634987, 'city_Mill Creek'),
 (0.0002518682653838601, 'job_Exhibition designer'),
 (0.0002515383277390118, 'merchant_fraud_Parisian and Sons'),
 (0.00025052396146799414, 'merchant_fraud_Kertzmann LLC'),
 (0.00025001354294717745, 'job_Engineer, automotive'),
 (0.00024977553355303556, 'merchant_fraud_Bogisich Inc'),
 (0.000248852283190709, 'street_79472 Stevens Trace Apt. 120'),
 (0.00024859292647004034, 'merchant_fraud_Weber, Thiel and Hammes'),
 (0.00024849002325078685, 'street_7309 Sophia Causeway Suite 702'),
 (0.0002458445054109322, 'street_92811 Jared Spur Apt. 345'),
 (0.0002456259481294127, 'job_Prison officer'),
 (0.00024549230873063805, 'merchant_fraud_Adams, Kovacek and Kuhlman'),
 (0.0002445043296328147, 'city_Randolph'),
 (0.00024354353042648063, 'merchant_fraud_Schaefer, Maggio and Daugherty'),
 (0.00024268963442907577, 'job_Special educational needs teacher'),
 (0.0002419540833249871, 'merchant_fraud_Turner, Ruecker and Parisian'),
 (0.0002417384686813253, 'job_Pharmacologist'),
 (0.00024163753308554614, 'street_334 Adam Mountains Apt. 868'),
 (0.00024075706950822329, 'street_901 Ariel Points'),
 (0.0002401555567765157, 'city_Tulsa'),
 (0.00023980122634886607, 'job_Health physicist'),
 (0.00023975170417495716, 'city_Knoxville'),
 (0.0002389276693186991, 'city_Fenelton'),
 (0.00023885499083527005, 'street_1984 Taylor Island Suite 836'),
 (0.00023842279811089602, 'merchant_fraud_Fisher Inc'),
 (0.0002378153913198786, 'merchant_fraud_Greenholt, Jacobi and Gleason'),
 (0.00023778383412158423, 'job_Chief Marketing Officer'),
 (0.0002376390971696403, 'merchant_fraud_Hills-Witting'),
 (0.00023718428626239184, 'job_Teacher, adult education'),
 (0.00023679688976055313, 'street_7618 Gonzales Mission'),
 (0.00023671733822956862, 'merchant_fraud_Douglas, DuBuque and McKenzie'),
 (0.00023669120465617759, 'merchant_fraud_Reichert, Rowe and Mraz'),
 (0.00023590922978318916, 'job_Systems developer'),
 (0.0002357639791393116, 'city_Bauxite'),
 (0.00023570411272374315, 'city_Shippingport'),
 (0.0002350415860514546, "merchant_fraud_Greenholt, O'Hara and Balistreri"),
 (0.0002341526119050534, 'street_8619 Lisa Manors Apt. 871'),
 (0.00023394755353049247, 'merchant_fraud_Barton LLC'),
 (0.0002330367782311478, 'job_Electrical engineer'),
 (0.00023192098301628712, 'job_Fitness centre manager'),
 (0.0002314210021654227, 'street_97405 Vazquez Plains'),
 (0.00023047549241600264, 'street_04975 Allison Shoal'),
 (0.000230194375350241, 'street_2481 Mills Lock'),
 (0.0002298915927812038, 'city_Belle Fourche'),
 (0.00022988890000288855, 'merchant_fraud_Kuhic Inc'),
 (0.0002297436270899479, 'merchant_fraud_Wolf Inc'),
 (0.00022965740520967213, 'street_08580 Jeremy Falls'),
 (0.00022914203556996068, 'job_Psychotherapist'),
 (0.00022912191770677796, 'merchant_fraud_Towne, Greenholt and Koepp'),
 (0.00022805120339765942, 'street_3896 Gilmore Mill'),
 (0.00022803409673083743, 'merchant_fraud_Eichmann-Kilback'),
 (0.00022761755556841137, 'job_Sub'),
 (0.00022752411044093678, 'job_Chief Strategy Officer'),
 (0.0002271628805631431, 'job_Fisheries officer'),
 (0.00022667257211189646, 'merchant_fraud_Metz-Boehm'),
 (0.00022651500609478299, 'city_Plainfield'),
 (0.00022641554703446384, 'city_West Hartford'),
 (0.00022584939123172044, 'merchant_fraud_Jast Ltd'),
 (0.00022493083853073574, 'merchant_fraud_Moen, Reinger and Murphy'),
 (0.00022486084723495413, 'street_5036 Victoria Ports Suite 249'),
 (0.00022381576348070933, 'merchant_fraud_Huels-Nolan'),
 (0.00022377904152997676,
  'merchant_fraud_Romaguera, Cruickshank and Greenholt'),
 (0.00022346042050027122, 'city_Blooming Grove'),
 (0.0002232207279870685, 'city_Holliday'),
 (0.0002231795936332659, 'merchant_fraud_Bins-Rice'),
 (0.00022293478059368733, 'job_Chiropodist'),
 (0.0002222871207321782, 'merchant_fraud_Baumbach, Strosin and Nicolas'),
 (0.00022175435197767122, 'job_Secretary/administrator'),
 (0.00022171461258192559, 'merchant_fraud_Ernser-Lynch'),
 (0.00022164330032478852, 'city_Center Point'),
 (0.00022157358131218055, 'street_25713 Hamilton Grove Apt. 903'),
 (0.00022139598673909816, 'street_2819 Luke Greens Suite 563'),
 (0.000221155730720036, 'street_458 Phillips Island Apt. 768'),
 (0.00022106858162483807, 'merchant_fraud_Casper, Hand and Zulauf'),
 (0.00022053235614521684, 'job_Copywriter, advertising'),
 (0.00022044661180554824, 'job_Economist'),
 (0.0002204118031776432, 'merchant_fraud_Schmeler, Bashirian and Price'),
 (0.00022038533763124216, 'city_New York City'),
 (0.00022032103033905925,
  'merchant_fraud_Christiansen, Goyette and Schamberger'),
 (0.0002202908637756325, 'merchant_fraud_Metz, Russel and Metz'),
 (0.00021966058006640674, 'job_Dealer'),
 (0.0002196564863811344, 'street_5270 Megan Burg Suite 756'),
 (0.00021944502132886307, 'city_Dallas'),
 (0.00021902523630335717, 'job_Chemical engineer'),
 (0.00021866539649174064, 'merchant_fraud_Goyette Inc'),
 (0.00021846303116428953, 'job_Music tutor'),
 (0.000218231992692517, 'job_Trade mark attorney'),
 (0.0002181555055440847, 'job_Commercial horticulturist'),
 (0.0002177067617447168, 'merchant_fraud_Brown PLC'),
 (0.0002175071986428058, 'job_Jewellery designer'),
 (0.00021684569752390944, 'street_537 Walker Freeway'),
 (0.0002165861581032878, 'merchant_fraud_Kutch, Hermiston and Farrell'),
 (0.00021637694155081277, 'street_87665 Karen Mill Apt. 586'),
 (0.0002162396626205004, 'state_NH'),
 (0.00021584489033304874, 'job_Television/film/video producer'),
 (0.0002157913759161483, 'job_Commercial/residential surveyor'),
 (0.0002152973297528948, 'city_Hancock'),
 (0.00021504760432755783, 'merchant_fraud_Jacobi Inc'),
 (0.00021455825106128385, 'state_CT'),
 (0.00021424696336664204, 'street_010 Salazar Walk'),
 (0.00021372729061824598, 'job_Animator'),
 (0.00021346051580886587, 'job_Radio broadcast assistant'),
 (0.0002134556888576338, 'job_Public relations account executive'),
 (0.0002134476330961615, 'merchant_fraud_Volkman Ltd'),
 (0.00021302658226599145, 'city_Fort Myers'),
 (0.0002126840650716799, 'street_589 Matthew Brooks'),
 (0.00021256265009673473, 'street_39218 Baker Shoals'),
 (0.00021222073980085542, 'city_Hinesburg'),
 (0.0002120770830085517, 'merchant_fraud_Kiehn-Emmerich'),
 (0.0002113869813558637, 'merchant_fraud_Dickinson Ltd'),
 (0.00021077065875314938, 'city_Washington'),
 (0.00021068561756999252, 'city_Breesport'),
 (0.0002102406473162389, 'city_Roma'),
 (0.00021000488247070815, 'street_82073 Jessica Camp'),
 (0.00020931571285255177, 'street_4900 Curtis Gardens Suite 952'),
 (0.0002090701376269932, 'merchant_fraud_Tillman, Dickinson and Labadie'),
 (0.00020875488308610995, 'street_8425 Daniel Knolls Suite 288'),
 (0.00020864679212378946, 'street_30587 Fox Shores Apt. 627'),
 (0.00020852412646737945, 'city_Matthews'),
 (0.00020843201088808222, 'street_3638 Marsh Union'),
 (0.0002083963911339803, 'job_Waste management officer'),
 (0.0002080883509175873, 'street_7055 Fernandez Estates Apt. 676'),
 (0.00020764957708379057, 'city_Sacramento'),
 (0.0002074126641079868, 'job_Special effects artist'),

Naive Random Oversampling

In [ ]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X, y)